name: mesh_app
description: Offline P2P Mesh Networking App

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wifi_iot: ^0.3.19+2    # Wi-Fi Direct
  qr_code_scanner: ^1.0.1 # QR Scanning
  file_picker: ^6.1.2      # File Transfer (from git to stable)
  permission_handler: ^12.0.0+1 # Permissions
  uuid: ^4.5.1            # Device IDs
  path_provider: ^2.1.1   # File handling


dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/qr_overlay.png